sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - 4.2
before_script:
  - npm prune
script:
  - npm run test
  - npm run build